### ISSUE TITLE
only works with  osx 10.12

### ISSUE THREAD

**Issue by razorfish-sl** [codilime/veles#161]
would be good if this could work with at-least the previous version of osx.

**Comment by adamiwaniuk** [comment]
Unfortunately we are not able to test it on previous OSX version. We made some change which might allow to run it on previous version. Could you check if it works for you? If yes, then this change will be included in next release.
[veles-osx.zip](https://github.com/codilime/veles/files/946949/veles-osx.zip)

**Comment by razorfish-sl** [comment]
Hi,
yes that fixed it

 I found i could run the old version by opening the  app folder and directly executing the bin file from the terminal.

so specifically it is just the OSX check related to the apps  os version check rather than any specific code issue

**Comment by adamiwaniuk** [comment]
Thanks for verifying the fix.
This server things aren't finished yet, so it is normal. We are still working on making it run without errors on all platforms. In your case probably cause of this behavior is missing python3. We expect that in released version it will be not needed to install it separately or appropriate error message will be displayed.
Again, thanks for feedback!
