### ISSUE TITLE
opening hex then selecting  "elf(ksy)" causes hard crash on osx

### ISSUE THREAD

**Issue by razorfish-sl** [codilime/veles#174]
uname -a
Darwin Macpro-2.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

 sw_vers -productVersion
10.11.6

[crash.txt.zip](https://github.com/codilime/veles/files/948666/crash.txt.zip)

**Comment by adamiwaniuk** [comment]
fix pushed to master
