### ISSUE TITLE
[Feature request] Hotkeys

### ISSUE THREAD

**Issue by disconnect3d** [codilime/veles#185]
It would be nice to have hotkeys for the RBM menu in hex editor (probably also for other stuff).

E.g.:
* CTRL+G -> Go to address
* CTRL+S -> Save to file

Also the hotkeys should be displayed in the menu items, so it would be easy to familiarize with them.

**Comment by mkow** [comment]
This feature is already scheduled for the June's release. We plan to have shortcuts for +/- everything and a shortcut editor. And maybe a command palette somewhen in the future ;)

**Comment by mkow** [comment]
Implemented and merged to master (including shortcut editor).
See https://github.com/codilime/veles/commit/bc0244852ab068ea0c1d2570f5b2f539a97f8fa9 and https://github.com/codilime/veles/commit/ac1a0ec91ed996c63dae1e2e52e2bd8295218992.
