### ISSUE TITLE
Builds on Windows should be multithreaded

### ISSUE THREAD

**Issue by mkow** [codilime/veles#259]

**Comment by wiktorn** [comment]
I've got this covered in 94858faab364a6e9d01ef663ceb9cb80b4c1b348

**Comment by mkow** [comment]
This fix still doesn't solve the problem (at least as I tested on my setup). I still got only one cl.exe running at a time and only one CPU was really used.

I think the problem is in cmake generating nmake files which invoke cl.exe separately for every .cc file (and passes /MP to this one-file compilation). /MP works only if you pass multiple source files, in this scenario the main cl.exe turns into a job server spawning another cl.exe processes.

**Comment by wiktorn** [comment]
#268 should get us as far with multi-threading as it is now on other platforms. So I'm closing this for now,
