### ISSUE TITLE
Specific usage CMAKE_OSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by upiter** [codilime/veles#333]
## Info
Current `Veles` version for `macOS` requires at least macOS Sierra: `10.12.4 (16E195)`
See [CMakeLists.txt](../blob/master/CMakeLists.txt)

## Details
- [CMake seems to ignore CMAKE_OSX_DEPLOYMENT_TARGET](https://stackoverflow.com/questions/34208360/cmake-seems-to-ignore-cmake-osx-deployment-target)
- [Confused about CMake's cached variable setting priority](https://stackoverflow.com/questions/26145865/confused-about-cmakes-cached-variable-setting-priority)

`set(CMAKE_OSX_DEPLOYMENT_TARGET "10.10" CACHE STRING "Minimum OS X deployment version")`
If not set explicitly as a cache variable the `CMAKE_OSX_DEPLOYMENT_TARGET` is initialised by the `MACOSX_DEPLOYMENT_TARGET` environment variable.

**Comment by mkow** [comment]
Thanks for spotting this! Could you please check whether #335 fixes the problem?
I've attached a .dmg file built after applying this change.

[veles-osx-req-version-fix.zip](https://github.com/codilime/veles/files/1310410/veles-osx-req-version-fix.zip)

**Comment by upiter** [comment]
Hi mkow,
thank you for updated version, but this doesn't help, sorry.

## Message when I try to launch Veles.app from /Applications:
```
You can’t use this version of the application “veles.app” with this version of OS X.
You have OS X 10.11.6. The application requires OS X 10.12 or later.
```
## And then I get this error when I launch via terminal:

```
Check with the developer to make sure veles works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Click Report to see more detailed information and send a report to Apple.
```

## When I execute from terminal:
```bash
/Applications/veles.app/Contents/MacOS/veles
```
I get output:
```bash
dyld: Library not loaded: @rpath/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/veles.app/Contents/MacOS/veles
  Reason: image not found
```

So, may be it's related to Qt too.

Additional info:
[Qt for macOS - Deployment](http://doc.qt.io/qt-5/osx-deployment.html)

**Comment by mkow** [comment]
Hmm, are you sure you downloaded the correct file? First file I attached in my response was improperly built (see #336, sorry for that!) and after about 15/20 minutes I reuploaded it. MD5 sum of the correct file:
bc6a0932c20e5c360f25a21d54a06856 *veles-osx-req-version-fix.dmg
The error you pasted (the problem with QtNetwork) looks exactly like the one caused by #336.

**Comment by upiter** [comment]
mkow,
I tried both files, but I'm still getting that error msg about OS version.

- veles-osx-req-version-fix.dmg
  - MD5 (old): `585d6c3933a424755685abec8366c49d`
  - MD5 (new): `bc6a0932c20e5c360f25a21d54a06856`
- veles-working.dmg
  - MD5: `bc6a0932c20e5c360f25a21d54a06856` (same as new veles-osx-req-version-fix.dmg)

Note: I succeeded with app from `dmg`, but failed to run from /Applications/

**Comment by mkow** [comment]
I'll try to find a device with macOS 10.11.6 and check if it's reproducible, without the device it may be hard to find a solution.

If you would manage to fix it anyhow please tell us (or just create pull request).

**Comment by mkow** [comment]
We couldn't reproduce the issue (because unfortunately we couldn't find any old macOS for tests), so closing this for now. I've also merged the proposed fix (#335).

@upiter Would you have time to test a package from the current master and check if the bug still occurs? If so, I'll build and attach it here. Otherwise I'll leave it closed, as we are neither able to reproduce this nor have enough manpower for a proper macOS support in general (non of us is using macOS).

**Comment by upiter** [comment]
@mkow I'll build from master and test build on OS X `10.11.6` El Capitan.
I'll report later.
Thank you for merging.

**Comment by mkow** [comment]
Great, thanks!
Could you also test a package built on some newer macOS? If you don't have access to any, I can build it on our buildserver and attach it here. I'd like to verify whether the issue occurs when a package is built on a newer macOS than it's run on.

**Comment by mkow** [comment]
Here you are. Please remove the ".txt" suffix, unfortunately GitHub doesn't allow uploading .dmg files.

[veles-osx.dmg.txt](https://github.com/codilime/veles/files/1879646/veles-osx.dmg.txt)

**Comment by upiter** [comment]
@mkow, just tested, everything works fine! Thank you so much!
Tested on:
- OS X (macOS) `10.11.6` El Capitan.

## Screen
<img width="1440" alt="veles - vlc" src="https://user-images.githubusercontent.com/795353/38433490-bd14a1cc-39d3-11e8-857f-c37dc3effd3e.png">

**Comment by mkow** [comment]
That's great :)
In case of any other problems please don't hesitate to submit an issue, we definitely lack proper testing on macOS.

**Comment by mkow** [comment]
Sure, thanks!
