### ISSUE TITLE
We should enable support for high-DPIs on macOS

### ISSUE THREAD

**Issue by mkow** [codilime/veles#340]
Current rendering on Retina (2560x1600):

![b2epgc8](https://user-images.githubusercontent.com/5244565/30595844-afab98a6-9d52-11e7-8286-265b97d38009.png)

**Comment by mkow** [comment]
Fixed package for tests: 
[veles-retina-fix.zip](https://github.com/codilime/veles/files/1314459/veles-retina-fix.zip)

**Comment by mkow** [comment]
Another try: 
[test.zip](https://github.com/codilime/veles/files/1314805/test.zip)

**Comment by ostefano** [comment]
Yup it works now
