### ISSUE TITLE
Cpplint issues

### ISSUE THREAD

**Issue by janczer** [codilime/veles#345]
I checked veles with [cpplint](https://github.com/google/styleguide), and cpplint have some issues about 80 characters:

```
src/parser/unpyc.cc:444:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/util/settings/connection_client.cc:218:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
```

**Comment by mkow** [comment]
I filled a bug in clang-format for the first case (https://bugs.llvm.org/show_bug.cgi?id=34693), the second one looks like an intended behavior for me - probably some compilers doesn't support splitting #warning strings well.
