### ISSUE TITLE
Dragging minimap causes assertion fail on small file.

### ISSUE THREAD

**Issue by prybicki** [codilime/veles#381]
Output: 
```
/veles/src/util/sampling/isampler.cc:84: 
size_t veles::util::ISampler::getFileOffset(size_t): 
Assertion `index <= sample_s' failed.
```

Click "Visualisation" button and try to drag minimap. Crashing file is attached.
[a.zip](https://github.com/codilime/veles/files/1518924/a.zip)

**Comment by mkow** [comment]
Confirmed.

**Comment by mkow** [comment]
Seems to be the same issue as #366.
